version: '3.9'
services:
  mongo1:
    image: mongo
    container_name: mongo1
    networks:
      - mongoCluster
    ports:
      - "27017:27017"
    command: "--replSet myReplicaSet"
  mongo2:
    image: mongo
    container_name: mongo2
    networks:
      - mongoCluster
    ports:
      - "27018:27017"
    command: "--replSet myReplicaSet"
  mongo3:
    image: mongo
    container_name: mongo3
    networks:
      - mongoCluster
    ports:
      - "27019:27017"
    command: "--replSet myReplicaSet"
  mongo-init:
    image: mongo
    container_name: mongo-init
    networks:
      - mongoCluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      mongo mongo1:27017/admin --eval "
      rs.initiate({
        _id: 'myReplicaSet',
        members: [
          { _id: 0, host: 'mongo1:27017' },
          { _id: 1, host: 'mongo2:27018' },
          { _id: 2, host: 'mongo3:27019' }
        ]
      });
      "
  yolo5app:
    image: 352708296901.dkr.ecr.us-east-2.amazonaws.com/edenb27-yolo5-app:V1
    container_name: yolo5app
    networks:
      - mongoCluster
    ports:
      - "8081:8081"
  telebot:
    image: 352708296901.dkr.ecr.us-east-2.amazonaws.com/edenb27-polybot-app:V1
    container_name: telebot
    networks:
      - mongoCluster
    ports:
      - "8443:8443"
    env_file:
      - .secret.env
networks:
  mongoCluster:
    driver: bridge